import { sql } from "./db"

export interface Specification {
  id: string
  workspace_id: string
  title: string
  control_number: string | null
  master_spec: string | null
  cost_analysis: string | null
  security_blueprint: string | null
  tech_stack_justification: string | null
  code_scaffolding: string | null
  created_by: string | null
  created_at: Date
  updated_at: Date
}

export async function getWorkspaceSpecifications(workspaceId: string): Promise<Specification[]> {
  const specs = await sql<Specification[]>`
    SELECT * FROM specifications
    WHERE workspace_id = ${workspaceId}
    ORDER BY created_at DESC
  `

  return specs
}

export async function createSpecification(data: {
  workspaceId: string
  title: string
  controlNumber: string
  masterSpec: string
  costAnalysis: string
  securityBlueprint: string
  techStackJustification: string
  codeScaffolding: string
  createdBy: string
}): Promise<Specification> {
  const specs = await sql<Specification[]>`
    INSERT INTO specifications (
      workspace_id, 
      title, 
      control_number,
      master_spec,
      cost_analysis,
      security_blueprint,
      tech_stack_justification,
      code_scaffolding,
      created_by
    )
    VALUES (
      ${data.workspaceId}, 
      ${data.title}, 
      ${data.controlNumber},
      ${data.masterSpec},
      ${data.costAnalysis},
      ${data.securityBlueprint},
      ${data.techStackJustification},
      ${data.codeScaffolding},
      ${data.createdBy}
    )
    RETURNING *
  `

  return specs[0]
}

export async function getSpecification(specId: string): Promise<Specification | null> {
  const specs = await sql<Specification[]>`
    SELECT * FROM specifications
    WHERE id = ${specId}
    LIMIT 1
  `

  return specs[0] || null
}

export async function createAutoGeneratedSpecification(
  workspaceId: string,
  title: string,
  userId: string,
  controlNumber: string,
  sections: {
    masterSpec: string
    costAnalysis: string
    securityBlueprint: string
    techStackJustification: string
    codeScaffolding: string
  },
): Promise<Specification> {
  const specs = await sql<Specification[]>`
    INSERT INTO specifications (
      workspace_id, 
      title, 
      control_number,
      master_spec,
      cost_analysis,
      security_blueprint,
      tech_stack_justification,
      code_scaffolding,
      created_by
    )
    VALUES (
      ${workspaceId}, 
      ${title}, 
      ${controlNumber},
      ${sections.masterSpec},
      ${sections.costAnalysis},
      ${sections.securityBlueprint},
      ${sections.techStackJustification},
      ${sections.codeScaffolding},
      ${userId}
    )
    RETURNING *
  `

  return specs[0]
}

export async function updateSpecification(
  specId: string,
  updates: Partial<
    Pick<
      Specification,
      "title" | "master_spec" | "cost_analysis" | "security_blueprint" | "tech_stack_justification" | "code_scaffolding"
    >
  >,
): Promise<Specification> {
  const setClauses: string[] = []
  const values: any[] = []

  if (updates.title !== undefined) {
    setClauses.push(`title = $${setClauses.length + 1}`)
    values.push(updates.title)
  }
  if (updates.master_spec !== undefined) {
    setClauses.push(`master_spec = $${setClauses.length + 1}`)
    values.push(updates.master_spec)
  }
  if (updates.cost_analysis !== undefined) {
    setClauses.push(`cost_analysis = $${setClauses.length + 1}`)
    values.push(updates.cost_analysis)
  }
  if (updates.security_blueprint !== undefined) {
    setClauses.push(`security_blueprint = $${setClauses.length + 1}`)
    values.push(updates.security_blueprint)
  }
  if (updates.tech_stack_justification !== undefined) {
    setClauses.push(`tech_stack_justification = $${setClauses.length + 1}`)
    values.push(updates.tech_stack_justification)
  }
  if (updates.code_scaffolding !== undefined) {
    setClauses.push(`code_scaffolding = $${setClauses.length + 1}`)
    values.push(updates.code_scaffolding)
  }

  setClauses.push(`updated_at = CURRENT_TIMESTAMP`)

  const specs = await sql<Specification[]>`
    UPDATE specifications
    SET ${sql.unsafe(setClauses.join(", "))}
    WHERE id = ${specId}
    RETURNING *
  `

  return specs[0]
}
